%% Kinova Gen3 7DOF
% Modified DH convention
% Peter Corke Robotics Toolbox

clc;
clear;

L(1) = RevoluteMDH( ...
    'd', 0.15643, ...
    'a', 0, ...
    'alpha', 0, ...
    'offset', 0);

L(2) = RevoluteMDH( ...
    'd', 0, ...
    'a', 0, ...
    'alpha', pi/2, ...
    'offset', 0);

L(3) = RevoluteMDH( ...
    'd', 0.21038, ...
    'a', 0, ...
    'alpha', -pi/2, ...
    'offset', 0);

L(4) = RevoluteMDH( ...
    'd', 0, ...
    'a', 0, ...
    'alpha', pi/2, ...
    'offset', 0);

L(5) = RevoluteMDH( ...
    'd', 0.20843, ...
    'a', 0, ...
    'alpha', -pi/2, ...
    'offset', 0);

L(6) = RevoluteMDH( ...
    'd', 0, ...
    'a', 0, ...
    'alpha', pi/2, ...
    'offset', 0);

L(7) = RevoluteMDH( ...
    'd', 0.10593, ...
    'a', 0, ...
    'alpha', -pi/2, ...
    'offset', 0);



GEN3 = SerialLink(L, 'name', 'KinovaGen3_7DOF');


q0 = zeros(1,7);

figure;
GEN3.teach(q0);
