clear; clc; close all;

%% MDH参数：[a, alpha, d]
MDH_params = [ ...
    0,  pi,   -0.1564-0.1284;
    0,  pi/2, -0.0054-0.0064;
    0, -pi/2, -0.2104-0.2104;
    0,  pi/2, -0.0064-0.0064;
    0, -pi/2, -0.2084-0.1059;
    0,  pi/2,  0;
    0, -pi/2, -0.0615-0.1059;
    0,  pi,    0];

%% 建立7个转动关节
L(1) = Link('revolute', 'modified', ...
    'a', MDH_params(1,1), ...
    'alpha', MDH_params(1,2), ...
    'd', MDH_params(1,3), ...
    'offset', 0);

L(2) = Link('revolute', 'modified', ...
    'a', MDH_params(2,1), ...
    'alpha', MDH_params(2,2), ...
    'd', MDH_params(2,3), ...
    'offset', 0);

L(3) = Link('revolute', 'modified', ...
    'a', MDH_params(3,1), ...
    'alpha', MDH_params(3,2), ...
    'd', MDH_params(3,3), ...
    'offset', 0);

L(4) = Link('revolute', 'modified', ...
    'a', MDH_params(4,1), ...
    'alpha', MDH_params(4,2), ...
    'd', MDH_params(4,3), ...
    'offset', 0);

L(5) = Link('revolute', 'modified', ...
    'a', MDH_params(5,1), ...
    'alpha', MDH_params(5,2), ...
    'd', MDH_params(5,3), ...
    'offset', 0);

L(6) = Link('revolute', 'modified', ...
    'a', MDH_params(6,1), ...
    'alpha', MDH_params(6,2), ...
    'd', MDH_params(6,3), ...
    'offset', 0);

L(7) = Link('revolute', 'modified', ...
    'a', MDH_params(7,1), ...
    'alpha', MDH_params(7,2), ...
    'd', MDH_params(7,3), ...
    'offset', 0);

%% 生成机器人模型
robot = SerialLink(L, 'name', '7DOF_MDH_Robot');

%% 第8行作为末端工具坐标系固定变换
a8 = MDH_params(8,1);
alpha8 = MDH_params(8,2);
d8 = MDH_params(8,3);

robot.tool = trotz(0) * transl(a8, 0, d8) * trotx(alpha8);

%% 初始关节角
q0 = zeros(1,7);

%% 显示机器人参数
robot.display();

%% 绘制机器人
figure;
robot.plot(q0, ...
    'workspace', [-1 1 -1 1 -1 1], ...
    'scale', 0.6);

title('7-DOF Robot Based on MDH Parameters');

%% 打开 teach 界面
robot.teach(q0);